spring.application.name=backend

# ===============================
# DATASOURCE CONFIGURATION
# ===============================
# Cambiar las credenciales si el usuario de postgres es distinto
spring.datasource.url=jdbc:postgresql://localhost:5432/logicode_orientador
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# HIBERNATE / JPA CONFIGURATION
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Permite que Hibernate cree y actualice automáticamente las tablas y columnas
spring.jpa.hibernate.ddl-auto=update

# Permite que Hibernate cree automáticamente los esquemas (academico, evaluacion, leads, chatbot)
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

# Mostrar logs de las consultas SQL (útil para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
